### PR TITLE
Internationalization support

### PR DESCRIPTION
**Pull request by ghost**
Here is a proposal to internationalize the app plus a French translation.
This should fix issue #4 .
Could you test this and give me a feedback?

### CODE REVIEW

**Comment by ghost** [comment]
Hello, could you please take some time to consider my pull request?
I thank you in advance.

**Comment by jaywink** [comment]
Hi @Anne017 

I'm sorry this PR has not been dealt with. Unfortunately I haven't been using the Ubuntu phone for some time. Currently I don't have a working device to test on. I guess the emulator might do, I will try to find time to set it up again.

**Comment by ghost** [comment]
Hello! Do you have some time to review this pull request?

**Comment by jaywink** [comment]
Hi @Anne017 

I'm unfortunately not able to help review this as I'm not an Ubuntu phone user any more. If you can find someone to adopt this app, I would gladly add that person committer rights, so they can move this forward.

Sorry.

**Pull request closed without merging**
